### PR TITLE
New sh fn executes in current shell process.

### PR DESCRIPTION
**Pull request by ProfAvery**
I found when trying to translate existing shell scripts that lines like
```
export FOO=bar
ulimit -n 2048
```
fail to have the desired effect because the commands run in a subshell. Added ``sh`` to run commands in the current shell instead.

The current implementation parses arguments like `sh!` but returns stdout like ``sh*``. There could be a version that parses output like ``sh!``, but I figured you'd mostly run commands like this for their side-effects and they'd return ``""``.

### CODE REVIEW

**Comment by chr15m** [comment]
Beautiful. Thanks for contributing this.

Some minor things:

 * Can we put this in extras.sh?
 * Can we consolidate the README and put it with the other sh variants?
 * Don't worry about committing docs/flk - I will do a build and put it in a separate commit.

Finally, this project seems to be proliferating `sh` variants. Is there some way we can merge this and use a flag instead? Something like `(sh* :env-local ...)`? Probably I should have done this with `sh!` and `sh*` too. :thinking:

Thanks again for submitting this, it looks very useful.

**Comment by chr15m** [comment]
When I say "merge this and use a flag instead" I'm not saying definitely do this, I'm more looking for feedback on how we can handle multiple versions of `sh` variants. All input welcome!

**Comment by ProfAvery** [comment]
I'm glad this seems useful. I originally left it separate because I wasn't sure if anyone else would have a need for it. Hopefully I've consolidated the code and README appropriately.

I agree that merging the various `sh` functions seems like a good idea, and it would be a good way to include the option for output parsing that I left out. Seems like two flags should do it:
 * One to decide whether to run in the current shell or in a subshell
 * Another to decide whether to return only stdout, or `[stdout stderr return-code]`.

(No idea what to recommend for flag names. Someone with more experience with Clojure is likely to have better taste.)

**Comment by chr15m** [comment]
After deliberating way too long I rename the function to `(sh-env ...)` to indicate that it modifies the local environment. Thank you for this contribution.

**Pull request merged**
